CREATE DATABASE roby;
USE roby;

CREATE TABLE User_roles(
    ID INT NOT NULL AUTO_INCREMENT,
    UserType VARCHAR(20) NOT NULL,
    PRIMARY KEY (ID)
);

INSERT INTO User_roles (UserType) VALUES ('Admin');
INSERT INTO User_roles (UserType) VALUES ('Customer');


CREATE TABLE COUNTRIES(COUNTRY_ID INT NOT NULL AUTO_INCREMENT, COUNTRY_NAME VARCHAR(25) NOT NULL, PRIMARY KEY(COUNTRY_ID));

INSERT INTO COUNTRIES (COUNTRY_NAME) VALUES ('Romania');
INSERT INTO COUNTRIES (COUNTRY_NAME) VALUES ('USA');
INSERT INTO COUNTRIES (COUNTRY_NAME) VALUES ('Luxembourg');
INSERT INTO COUNTRIES (COUNTRY_NAME) VALUES ('Afganistan');


CREATE TABLE PPL (
    PERSON_ID INT NOT NULL AUTO_INCREMENT, 
    First_Name VARCHAR(25) NOT NULL, 
    Second_Name VARCHAR(25) NOT NULL,
    Age INT,
    UserName VARCHAR(25) NOT NULL UNIQUE,
    Password VARCHAR(200) NOT NULL,
    Nationality INT NOT NULL,
    UsrType INT NOT NULL,
    PRIMARY KEY (PERSON_ID),
    FOREIGN KEY (Nationality) REFERENCES COUNTRIES(COUNTRY_ID),
    FOREIGN KEY (UsrType) REFERENCES User_roles(ID)
);
